In [ ]:
!wget --no-check-certificate https://files.grouplens.org/datasets/movielens/ml-100k.zip

--2021-04-15 00:08:05--  https://files.grouplens.org/datasets/movielens/ml-100k.zip
Resolving files.grouplens.org (files.grouplens.org)... 128.101.65.152
Connecting to files.grouplens.org (files.grouplens.org)|128.101.65.152|:443... connected.
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 4924029 (4.7M) [application/zip]
Saving to: ‘ml-100k.zip.2’

ml-100k.zip.2       100%[===================>]   4.70M  11.0MB/s    in 0.4s    

2021-04-15 00:08:05 (11.0 MB/s) - ‘ml-100k.zip.2’ saved [4924029/4924029]



In [ ]:
import numpy as np
import pandas as pd 

In [ ]:
import shutil
shutil.unpack_archive("/content/ml-100k.zip", "/content/dataset")

In [ ]:
columns_name=['user_id',"item_id","rating","timestamp"]
df=pd.read_csv("/content/dataset/ml-100k/u.data",sep='\t',names=columns_name)

In [ ]:
df.head()

user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [ ]:
print(df.size)
print(df.shape)

400000
(100000, 4)


In [ ]:
movies_title = pd.read_csv("/content/dataset/ml-100k/u.item", sep="\|",header= None,encoding='latin-1')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [ ]:
movies_title.head()

0                  1            2   3   ... 20  21  22  23
0   1   Toy Story (1995)  01-Jan-1995 NaN  ...  0   0   0   0
1   2   GoldenEye (1995)  01-Jan-1995 NaN  ...  0   1   0   0
2   3  Four Rooms (1995)  01-Jan-1995 NaN  ...  0   1   0   0
3   4  Get Shorty (1995)  01-Jan-1995 NaN  ...  0   0   0   0
4   5     Copycat (1995)  01-Jan-1995 NaN  ...  0   1   0   0

[5 rows x 24 columns]

In [ ]:
movies_title=movies_title[[0,1]]
movies_title.columns=['item_id','title']
movies_title.head()

item_id              title
0        1   Toy Story (1995)
1        2   GoldenEye (1995)
2        3  Four Rooms (1995)
3        4  Get Shorty (1995)
4        5     Copycat (1995)

In [ ]:
print(movies_title.size)
print(movies_title.shape)

3364
(1682, 2)


In [ ]:
print(len(movies_title.title.unique()))
movies_title.item_id.unique()

1664


array([   1,    2,    3, ..., 1680, 1681, 1682])

In [ ]:
#print(len(movies_title.item_id.unique()))
#print(len(df.item_id.unique()))

In [ ]:
#print("Number of null values in column 1 : "+str(movies_title.iloc[:, 1].isnull().sum()))

In [ ]:
print(len(df.user_id.unique()))
l=df.user_id.unique()
#l.sort()
l

943


array([196, 186,  22, 244, 166, 298, 115, 253, 305,   6,  62, 286, 200,
       210, 224, 303, 122, 194, 291, 234, 119, 167, 299, 308,  95,  38,
       102,  63, 160,  50, 301, 225, 290,  97, 157, 181, 278, 276,   7,
        10, 284, 201, 287, 246, 242, 249,  99, 178, 251,  81, 260,  25,
        59,  72,  87,  42, 292,  20,  13, 138,  60,  57, 223, 189, 243,
        92, 241, 254, 293, 127, 222, 267,  11,   8, 162, 279, 145,  28,
       135,  32,  90, 216, 250, 271, 265, 198, 168, 110,  58, 237,  94,
       128,  44, 264,  41,  82, 262, 174,  43,  84, 269, 259,  85, 213,
       121,  49, 155,  68, 172,  19, 268,   5,  80,  66,  18,  26, 130,
       256,   1,  56,  15, 207, 232,  52, 161, 148, 125,  83, 272, 151,
        54,  16,  91, 294, 229,  36,  70,  14, 295, 233, 214, 192, 100,
       307, 297, 193, 113, 275, 219, 218, 123, 158, 302,  23, 296,  33,
       154,  77, 270, 187, 170, 101, 184, 112, 133, 215,  69, 104, 240,
       144, 191,  61, 142, 177, 203,  21, 197, 134, 180, 236, 26

In [ ]:
df=pd.merge(df,movies_title,on="item_id",how = 'inner')
df.tail()

user_id  ...                                              title
99995      840  ...                                  Mamma Roma (1962)
99996      655  ...                             Eighth Day, The (1996)
99997      655  ...                                  Girls Town (1996)
99998      655  ...  Silence of the Palace, The (Saimt el Qusur) (1...
99999      655  ...                                    Dadetown (1995)

[5 rows x 5 columns]

In [ ]:
ratings_matrix_items = df.pivot_table(index=['user_id'],columns=['title'],values='rating')#.reset_index(drop=True)


In [ ]:
ratings_matrix_items.head()

title    'Til There Was You (1997)  ...  Á köldum klaka (Cold Fever) (1994)
user_id                             ...                                    
1                              NaN  ...                                 NaN
2                              NaN  ...                                 NaN
3                              NaN  ...                                 NaN
4                              NaN  ...                                 NaN
5                              NaN  ...                                 NaN

[5 rows x 1664 columns]

In [ ]:
user_movies=ratings_matrix_items.copy()

In [ ]:
ratings_matrix_items.tail()

title    'Til There Was You (1997)  ...  Á köldum klaka (Cold Fever) (1994)
user_id                             ...                                    
939                            NaN  ...                                 NaN
940                            NaN  ...                                 NaN
941                            NaN  ...                                 NaN
942                            NaN  ...                                 NaN
943                            NaN  ...                                 NaN

[5 rows x 1664 columns]

In [ ]:
print(ratings_matrix_items.shape)
print(ratings_matrix_items.max().max())
print(ratings_matrix_items.min().min())

(943, 1664)
5.0
1.0


In [ ]:
ratings_matrix_items.fillna( 0, inplace = True )

In [ ]:
ratings_matrix_items.head()

title    'Til There Was You (1997)  ...  Á köldum klaka (Cold Fever) (1994)
user_id                             ...                                    
1                              0.0  ...                                 0.0
2                              0.0  ...                                 0.0
3                              0.0  ...                                 0.0
4                              0.0  ...                                 0.0
5                              0.0  ...                                 0.0

[5 rows x 1664 columns]

In [ ]:
def funksvd(matrix,latent,lr,iteration):
    np.random.seed(52)
    users = matrix.shape[0]
    movies = matrix.shape[1]
    squared_error = 0
    user = np.random.rand(users,latent)
    movie = np.random.rand(latent,movies)
    number_of_ratings=100000
    print("Iterations | Mean Squared Error ")
    for i4 in range(iteration):
        squared_error = 0
        for i in range(users):
            for j in range(movies):
                if (matrix[i, j] !=0.0):
                    difference = matrix[i, j] - np.dot(user[i, :], movie[:, j])
                    squared_error=squared_error+difference**2
                    for k in range(latent):
                        user[i, k] += lr * (2*difference*movie[k, j])
                        movie[k, j] += lr * (2*difference*user[i, k])
        print("%d \t\t %f" % (i4+1,squared_error/ number_of_ratings))
    
    return movie,user

In [ ]:
import time

In [ ]:
start_time = time.time()
movie,user=funksvd(ratings_matrix_items.values,4,0.0001,11)
print("--- %s seconds ---" % (time.time() - start_time))

Iterations | Mean Squared Error 
1 		 7.177512
2 		 6.253187
3 		 5.391844
4 		 4.625579
5 		 3.972752
6 		 3.436695
7 		 3.008581
8 		 2.672469
9 		 2.410212
10 		 2.204850
11 		 2.042265
--- 29.22285008430481 seconds ---


In [ ]:
ratings_matrix_items.values

array([[0., 0., 2., ..., 0., 4., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
movie

array([[0.38106775, 0.03255656, 0.31583307, ..., 0.18754135, 0.59873882,
        0.148736  ],
       [0.03849877, 0.30801043, 0.39890624, ..., 0.46253962, 0.97475313,
        0.43383179],
       [0.55197363, 0.97828285, 1.01895724, ..., 0.01495084, 0.19781987,
        0.14955277],
       [0.02637017, 0.76265427, 0.74135972, ..., 0.13439696, 0.68105231,
        0.58810854]])

In [ ]:
user

array([[1.35565432, 0.58293667, 0.78155065, 1.14970131],
       [0.31189369, 0.81050789, 0.25262421, 1.13853163],
       [1.01419893, 0.56127476, 0.68099087, 0.82689336],
       ...,
       [0.86439451, 0.32601002, 0.43694686, 0.15403371],
       [0.51737299, 0.59497474, 0.63792878, 0.50901115],
       [0.87270376, 1.02306135, 0.83523222, 0.77399412]])

In [ ]:
svd_result=np.dot(user,movie)
svd_result

array([[1.00075166, 1.86508822, 2.30940647, ..., 0.69007376, 2.3175152 ,
        1.24756329],
       [0.31952136, 1.37524302, 1.52329776, ..., 0.59017711, 1.80216165,
        1.10537474],
       [0.80578122, 1.50273275, 1.85113957, ..., 0.5711294 , 1.85221576,
        0.98249385],
       ...,
       [0.5871889 , 0.67348828, 0.96247636, ..., 0.34013665, 1.02666763,
        0.42593525],
       [0.58560254, 1.21237663, 1.42812516, ..., 0.45017535, 1.362583  ,
        0.72982877],
       [0.85338238, 1.75090907, 2.10860825, ..., 0.75338433, 2.21210989,
        1.15374285]])

In [ ]:
svd_result.shape

(943, 1664)

In [ ]:
data = pd.DataFrame(data =svd_result)
print(data.max().max())
print(data.min().min())

6.82821269830454
0.03467975762490103


In [ ]:
column_values=list(ratings_matrix_items.columns)
len(column_values)

1664

In [ ]:
index=list(ratings_matrix_items.index)
#index

In [ ]:
data=pd.DataFrame(data = svd_result, index = index,columns = column_values)
data.head()

'Til There Was You (1997)  ...  Á köldum klaka (Cold Fever) (1994)
1                   1.000752  ...                            1.247563
2                   0.319521  ...                            1.105375
3                   0.805781  ...                            0.982494
4                   0.826607  ...                            0.777882
5                   0.773051  ...                            1.206031

[5 rows x 1664 columns]

In [ ]:
print(data.shape)

(943, 1664)


In [ ]:
from sparsesvd import sparsesvd
from scipy.sparse.linalg import *

In [ ]:
pip install sparsesvd

In [ ]:
ratings_matrix_items.head()

title    'Til There Was You (1997)  ...  Á köldum klaka (Cold Fever) (1994)
user_id                             ...                                    
1                              0.0  ...                                 0.0
2                              0.0  ...                                 0.0
3                              0.0  ...                                 0.0
4                              0.0  ...                                 0.0
5                              0.0  ...                                 0.0

[5 rows x 1664 columns]

In [ ]:
user_means = np.array(ratings_matrix_items.mean(axis = 1)).reshape(-1, 1)
svd_movies = ratings_matrix_items.div(ratings_matrix_items.mean(axis = 1), axis = 0)
svd_movies_matrix = svd_movies.values

In [ ]:
start_time = time.time()
U, sigma, Vt = svds(svd_movies_matrix)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.1144266128540039 seconds ---


In [ ]:
sigma = np.diag(sigma)

In [ ]:
predicted = np.dot(np.dot(U, sigma), Vt)
predicted_ratings = np.dot(np.dot(U, sigma), Vt) * user_means

In [ ]:
predicted_ratings

array([[ 3.49312870e-02,  3.52571979e-02,  5.17065333e-01, ...,
         1.37598831e-02,  4.21769960e-02,  9.19278325e-04],
       [ 4.44584904e-03,  5.67490417e-02,  2.37977590e-01, ...,
         2.25157396e-02,  7.39843441e-03,  1.92009646e-04],
       [-1.85394322e-03, -1.68787073e-02, -2.07173685e-02, ...,
        -4.33724353e-03,  5.63815099e-02,  2.57357102e-05],
       ...,
       [ 1.97197828e-03,  8.28747562e-03,  2.61015267e-01, ...,
         1.56813509e-02,  4.79947488e-03, -2.55606132e-05],
       [ 2.18204391e-02, -1.20825308e-02,  1.49500815e-01, ...,
        -8.09267671e-03, -4.49820211e-03,  3.39951228e-04],
       [ 2.22792532e-02, -6.38316124e-04,  4.21707185e-01, ...,
         1.05476888e-02,  3.44216545e-02,  5.02600836e-04]])

In [ ]:
svd_prediction=pd.DataFrame(data = predicted_ratings,index = index,columns = column_values)
svd_prediction.head()

'Til There Was You (1997)  ...  Á köldum klaka (Cold Fever) (1994)
1                   0.034931  ...                            0.000919
2                   0.004446  ...                            0.000192
3                  -0.001854  ...                            0.000026
4                   0.000604  ...                            0.000004
5                   0.018837  ...                            0.000380

[5 rows x 1664 columns]

In [ ]:
def svd_recommender(df_predict, user, umr, number_recomm):
    user_predicted_movies = df_predict.loc[user, :].sort_values(ascending = False)
    original_data = umr.loc[user, :].sort_values(ascending = False)
    already_rated = user_movies.loc[user, :].dropna()
    unrated = list(user_movies.loc[1, pd.isnull(user_movies.loc[user, :])].index)   
    recommendations = df_predict.loc[user][unrated]  
    recommendations = pd.DataFrame(recommendations.sort_values(ascending = False).index[:number_recomm])  
    return recommendations, already_rated

In [ ]:
#svd recommendations
recommend, rated = svd_recommender(svd_prediction, 7, svd_movies, 10)
#user id 7
print(recommend)

                                                   0
0                                   Toy Story (1995)
1                          This Is Spinal Tap (1984)
2                      Much Ado About Nothing (1993)
3                        Sleepless in Seattle (1993)
4                    Star Trek: First Contact (1996)
5                                     Aladdin (1992)
6                         Wrong Trousers, The (1993)
7                         Singin' in the Rain (1952)
8  Like Water For Chocolate (Como agua para choco...
9                                 Hoop Dreams (1994)


In [ ]:
#funk_svd recommendations
recommend, rated = svd_recommender(data, 7, svd_movies, 10)
#user id 7
print(recommend)

                                 0
0         L.A. Confidential (1997)
1                   Titanic (1997)
2                 Toy Story (1995)
3                 Rock, The (1996)
4              Men in Black (1997)
5        Mr. Holland's Opus (1995)
6             Donnie Brasco (1997)
7             Trainspotting (1996)
8         Good Will Hunting (1997)
9  Star Trek: First Contact (1996)


In [ ]:
funk-svd(11 iterations, 4 latent factors): 29.22285008430481 seconds
svd                                      : 0.1144266128540039 seconds

In [ ]:
pip install surprise

In [ ]:
from surprise import SVD
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split

# Load the movielens-100k dataset (download it if needed),
data = Dataset.load_builtin('ml-100k')

# sample random trainset and testset
# test set is made of 25% of the ratings.
trainset, testset = train_test_split(data, test_size=.25)

# We'll use the famous SVD algorithm.
algo = SVD()

# Train the algorithm on the trainset, and predict ratings for the testset
algo.fit(trainset)
predictions = algo.test(testset)

# Then compute RMSE
accuracy.rmse(predictions)

RMSE: 0.9355


0.9354517176557257

In [ ]:
predictions

[Prediction(uid='942', iid='174', r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid='326', iid='448', r_ui=3.0, est=2.830777820707803, details={'was_impossible': False}),
 Prediction(uid='305', iid='166', r_ui=4.0, est=3.5754786504528155, details={'was_impossible': False}),
 Prediction(uid='330', iid='151', r_ui=4.0, est=4.436433414123742, details={'was_impossible': False}),
 Prediction(uid='7', iid='265', r_ui=5.0, est=4.497935293197379, details={'was_impossible': False}),
 Prediction(uid='798', iid='163', r_ui=3.0, est=3.6277870568045976, details={'was_impossible': False}),
 Prediction(uid='795', iid='150', r_ui=3.0, est=3.7165655990397104, details={'was_impossible': False}),
 Prediction(uid='63', iid='1011', r_ui=1.0, est=3.010921448640712, details={'was_impossible': False}),
 Prediction(uid='308', iid='1028', r_ui=2.0, est=3.3672451266284833, details={'was_impossible': False}),
 Prediction(uid='490', iid='124', r_ui=4.0, est=3.1895624077264655, details={'was_impo

In [ ]:
import multiprocessing

In [ ]:
def parallel_funksvd(matrix):
    np.random.seed(52)
    users = matrix.shape[0]
    movies = matrix.shape[1]
    squared_error = 0
    user = np.random.rand(users,4)
    movie = np.random.rand(4,movies)
    for i4 in range(4):
        squared_error = 0
        for i in range(users):
            for j in range(movies):
                if (matrix[i, j] !=0.0):
                    difference = matrix[i, j] - np.dot(user[i, :], movie[:, j])
                    squared_error=squared_error+difference**2
                    for k in range(latent):
                        user[i, k] += 0.0001 * (2*difference*movie[k, j])
                        movie[k, j] += 0.0001 * (2*difference*user[i, k])
    svd_parallel=np.dot(user,movie)
    return svd_parallel

In [ ]:
if __name__ == "__main__": 
  start_time = time.time()
  pool = multiprocessing.Pool(processes=2)
  result = pool.map(parallel_funksvd,[part,part2])
  print("--- %s seconds ---" % (time.time() - start_time))
  result_parallel=result[0]+result[1]
  print(result_parallel)
  print(len(result_parallel))

NameError: ignored

In [ ]:
part=

In [ ]:
!pip install pymp-pypi

In [ ]:
import pymp

In [ ]:
start_time = time.time()
with pymp.Parallel(2) as p:
    for index in p.range(0,n):
      for j in range(n): 
        for k in range(n): 
          result_parallel[index][j] += l1[index][k] * l2[k][j] 
print("--- %s seconds ---" % (time.time() - start_time))
print(result_parallel)

In [ ]:
matrix=ratings_matrix_items.copy()

In [ ]:
np.random.seed(52)
users = matrix.shape[0]
movies = matrix.shape[1]
user = pymp.shared.array((users,4))
movie = pymp.shared.array((4,movies))
for i4 in range(4):
  with pymp.Parallel(2) as p:
    for i in p.range(0,users):
      for j in range(movies):
        print(i)
        if (matrix[i, j] !=0.0):
          difference = matrix[i, j] - np.dot(user[i, :], movie[:, j])
          squared_error=squared_error+difference**2
          for k in range(latent):
            user[i, k] += 0.0001 * (2*difference*movie[k, j])
            movie[k, j] += 0.0001 * (2*difference*user[i, k])
svd_parallel=np.dot(user,movie)

In [ ]:
result_parallel= pymp.shared.array(943, 1664)
ressult_parallel=

In [ ]:
np.random.seed(52)
users = matrix.shape[0]
movies = matrix.shape[1]
user = pymp.shared.array((users,4))
movie = pymp.shared.array((4,movies))
print(type(movie))